In [2]:
import pandas as pd

In [3]:
pd.read_excel("Attribute DataSet.xlsx")

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid,1
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [10]:
df=pd.read_excel(r'D:\pandas data set\fsdl data\Attribute DataSet.xlsx')

In [11]:
df

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid,1
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [24]:
df=pd.read_excel(r'D:\pandas data set\fsdl data\Attribute DataSet.xlsx')

In [25]:
df

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid,1
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [26]:
type(df)

pandas.core.frame.DataFrame

In [30]:
pd.read_excel(r'D:\pandas data set\fsdl data\Attribute DataSet.xlsx',sheet_name='sudh',header=None,names=['A','B','C'])

         A        B        C
0   thdgfd   hdghjf  ghgdfhf
1       jh       jh       jh
2    kdjfk    kdjfk    kdjfk
3     jkfh     jkfh     jkfh
4  hfjfhfj  hfjfhfj  hfjfhfj
5    hjdte    hjdte    hjdte
6   hdjdhf   hdjdhf   hdjdhf
7    hjfhf    hjfhf    hjfhf
8    djhfj    djhfj    djhfj

In [31]:
pd.read_excel(r'D:\pandas data set\fsdl data\Attribute DataSet.xlsx',sheet_name='kumar')

    thdgfd  jh  kdjfk  jkfh  hfjfhfj  hjdte  hdjdhf  hjfhf  djhfj
0   hdghjf  jh  kdjfk  jkfh  hfjfhfj  hjdte  hdjdhf  hjfhf  djhfj
1  ghgdfhf  jh  kdjfk  jkfh  hfjfhfj  hjdte  hdjdhf  hjfhf  djhfj

In [32]:
df

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid,1
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [33]:
df.head(2)

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0

In [34]:
df.tail()

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid,1
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [35]:
df.tail(3)

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [38]:
pd.read_csv(r'D:\pandas data set\fsdl data\haberman.csv',header=None,names=['age',"Patient's year of op",'Number of positive','Survival status'])

     age  Patient's year of op  Number of positive  Survival status
0     30                    64                   1                1
1     30                    62                   3                1
2     30                    65                   0                1
3     31                    59                   2                1
4     31                    65                   4                1
..   ...                   ...                 ...              ...
301   75                    62                   1                1
302   76                    67                   0                1
303   77                    65                   3                1
304   78                    65                   1                2
305   83                    58                   2                2

[306 rows x 4 columns]

In [10]:
pd.read_csv(r'D:\pandas data set\fsdl data\haberman1.csv')

      30@64@1@1
0     30@62@3@1
1     30@65@0@1
2     31@59@2@1
3     31@65@4@1
4    33@58@10@1
..          ...
300   75@62@1@1
301   76@67@0@1
302   77@65@3@1
303   78@65@1@2
304   83@58@2@2

[305 rows x 1 columns]

In [8]:
pd.read_csv(r'D:\pandas data set\fsdl data\haberman1.csv',sep='@')

     30  64   1  1.1
0    30  62   3    1
1    30  65   0    1
2    31  59   2    1
3    31  65   4    1
4    33  58  10    1
..   ..  ..  ..  ...
300  75  62   1    1
301  76  67   0    1
302  77  65   3    1
303  78  65   1    2
304  83  58   2    2

[305 rows x 4 columns]

In [12]:
pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BCF.csv')

           date  values.I2P  values.P2I  values.JPI
0    1996-04-01   -2.580556   -0.836444        63.3
1    1996-05-01   -2.882258   -1.972581        66.3
2    1996-06-01   -1.742778   -0.478778        59.7
3    1996-07-01   -0.397796   -1.574301        63.3
4    1996-08-01   -0.977151   -1.797312        63.8
..          ...         ...         ...         ...
112  2005-08-01   -2.144935   -1.646989        49.0
113  2005-09-01   -3.543270   -1.769889        49.9
114  2005-10-01   -4.500484   -2.309946        50.6
115  2005-11-01   -4.098556   -1.528611        57.4
116  2005-12-01   -5.797043   -2.872849        52.9

[117 rows x 4 columns]

In [15]:
pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Smarket.csv')

      Year   Lag1   Lag2   Lag3   Lag4   Lag5   Volume  Today Direction
0     2001  0.381 -0.192 -2.624 -1.055  5.010  1.19130  0.959        Up
1     2001  0.959  0.381 -0.192 -2.624 -1.055  1.29650  1.032        Up
2     2001  1.032  0.959  0.381 -0.192 -2.624  1.41120 -0.623      Down
3     2001 -0.623  1.032  0.959  0.381 -0.192  1.27600  0.614        Up
4     2001  0.614 -0.623  1.032  0.959  0.381  1.20570  0.213        Up
...    ...    ...    ...    ...    ...    ...      ...    ...       ...
1245  2005  0.422  0.252 -0.024 -0.584 -0.285  1.88850  0.043        Up
1246  2005  0.043  0.422  0.252 -0.024 -0.584  1.28581 -0.955      Down
1247  2005 -0.955  0.043  0.422  0.252 -0.024  1.54047  0.130        Up
1248  2005  0.130 -0.955  0.043  0.422  0.252  1.42236 -0.298      Down
1249  2005 -0.298  0.130 -0.955  0.043  0.422  1.38254 -0.489      Down

[1250 rows x 9 columns]

In [17]:
a=pd.read_html('https://www.basketball-reference.com/leagues/NBA_2015_totals.html')

In [18]:
type(a)

list

In [19]:
len(a)

1

In [20]:
a[0]

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Quincy Acy,PF,24,NYK,68,22,1287,152,331,...,.784,79,222,301,68,27,22,60,147,398
1,2,Jordan Adams,SG,20,MEM,30,0,248,35,86,...,.609,9,19,28,16,16,7,14,24,94
2,3,Steven Adams,C,21,OKC,70,67,1771,217,399,...,.502,199,324,523,66,38,86,99,222,537
3,4,Jeff Adrien,PF,28,MIN,17,0,215,19,44,...,.579,23,54,77,15,4,9,9,30,60
4,5,Arron Afflalo,SG,29,TOT,78,72,2502,375,884,...,.843,27,220,247,129,41,7,116,167,1035
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,490,Thaddeus Young,PF,26,TOT,76,68,2434,451,968,...,.655,127,284,411,173,124,25,117,171,1071
671,490,Thaddeus Young,PF,26,MIN,48,48,1605,289,641,...,.682,75,170,245,135,86,17,75,115,685
672,490,Thaddeus Young,PF,26,BRK,28,20,829,162,327,...,.606,52,114,166,38,38,8,42,56,386
673,491,Cody Zeller,C,22,CHO,62,45,1487,172,373,...,.774,97,265,362,100,34,49,62,156,472
674,492,Tyler Zeller,C,25,BOS,82,59,1731,340,619,...,.823,146,319,465,113,18,52,76,205,833

In [21]:
a

[      Rk          Player Pos Age   Tm   G  GS    MP   FG  FGA  ...   FT%  ORB  \
 0      1      Quincy Acy  PF  24  NYK  68  22  1287  152  331  ...  .784   79
 1      2    Jordan Adams  SG  20  MEM  30   0   248   35   86  ...  .609    9
 2      3    Steven Adams   C  21  OKC  70  67  1771  217  399  ...  .502  199
 3      4     Jeff Adrien  PF  28  MIN  17   0   215   19   44  ...  .579   23
 4      5   Arron Afflalo  SG  29  TOT  78  72  2502  375  884  ...  .843   27
 ..   ...             ...  ..  ..  ...  ..  ..   ...  ...  ...  ...   ...  ...
 670  490  Thaddeus Young  PF  26  TOT  76  68  2434  451  968  ...  .655  127
 671  490  Thaddeus Young  PF  26  MIN  48  48  1605  289  641  ...  .682   75
 672  490  Thaddeus Young  PF  26  BRK  28  20   829  162  327  ...  .606   52
 673  491     Cody Zeller   C  22  CHO  62  45  1487  172  373  ...  .774   97
 674  492    Tyler Zeller   C  25  BOS  82  59  1731  340  619  ...  .823  146

      DRB  TRB  AST  STL BLK  TOV   PF   PTS
 0    222  301   68   27  22   60  147   398
 1     19   28   16   16   7   14   24    94
 2    324  523   66   38  86   99  222   537
 3     54   77   15    4   9    9   30    60
 4    220  247  129   41   7  116  167  1035
 ..   ...  ...  ...  ...  ..  ...  ...   ...
 670  284  411  173  124  25  117  171  1071
 671  170  245  135   86  17   75  115   685
 672  114  166   38   38   8   42   56   386
 673  265  362  100   34  49   62  156   472
 674  319  465  113   18  52   76  205   833

 [675 rows x 30 columns]]

In [24]:
js=pd.read_json('https://api.github.com/repos/pandas-dev/pandas/issues')

In [25]:
js

,url,repository_url,labels_url,comments_url,events_url,html_url,id,node_id,number,title,...,closed_at,author_association,active_lock_reason,body,reactions,timeline_url,performed_via_github_app,state_reason,draft,pull_request
0,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/49894,1463455548,I_kwDOAA0YD85XOo88,49894,BUILD: pandas 1.5.2 can't be installed with co...,...,NaT,NONE,NaN,### Installation check\n\n- [X] I have read th...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,NaN,NaN
1,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/49893,1463439055,PR_kwDOAA0YD85Dpsio,49893,BUG: Do not attempt to parse datetime.datetime...,...,NaT,MEMBER,NaN,- [x] closes #49298 (Replace xxxx with the Git...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,0.0,{'url': 'https://api.github.com/repos/pandas-d...
2,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/49892,1463438427,PR_kwDOAA0YD85DpsZ8,49892,DEPR: Change numeric_only to False in various ...,...,NaT,MEMBER,NaN,- [ ] closes #xxxx (Replace xxxx with the GitH...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,0.0,{'url': 'https://api.github.com/repos/pandas-d...
3,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/49890,1463418878,PR_kwDOAA0YD85DpoOn,49890,BUG: Series(nullable).tolist() -> numpy scalars,...,NaT,CONTRIBUTOR,NaN,- [x] [Tests added and passed](https://pandas....,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,0.0,{'url': 'https://api.github.com/repos/pandas-d...
4,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/49889,1463413890,I_kwDOAA0YD85XOeyC,49889,BUG: categorical_column_to_series() should not...,...,NaT,NONE,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,NaN,NaN
5,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/49888,1463385108,I_kwDOAA0YD85XOXwU,49888,BUG: bitmasks not supported in interchange/fro...,...,NaT,NONE,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,NaN,NaN
6,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/49884,1462659891,PR_kwDOAA0YD85DnEfu,49884,STYLE: fix pylint style checks for access-memb...,...,NaT,CONTRIBUTOR,NaN,- [ ] xref #48855\r\n- [X] All [code checks pa...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,0.0,{'url': 'https://api.github.com/repos/pandas-d...
7,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/49881,1462592019,I_kwDOAA0YD85XLWIT,49881,DOC: read_csv default encoding is not documented,...,NaT,CONTRIBUTOR,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,NaN,NaN
8,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/49880,1462574302,PR_kwDOAA0YD85DmyQo,49880,48855 style fix pylint issues pointless string...,...,NaT,CONTRIBUTOR,NaN,- [ ] closes #xxxx (Replace xxxx with the GitH...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,0.0,{'url': 'https://api.github.com/repos/pandas-d...
9,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/49878,1462560491,I_kwDOAA0YD85XLObr,49878,BUG: groupby rolling apply giving strange index,...,NaT,NONE,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,NaN,NaN
10,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/49877,1462533667,PR_kwDOAA0YD85DmpVC,49877,BUG: MultiIndex.join losing dtype,...,NaT,MEMBER,NaN,- [x] closes #49830 (Replace xxxx with the Git...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,0.0,{'url': 'https://api.github.com/repos/pandas-d...
11,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/49876,1462498496,PR_kwDOAA0YD85DmhY4,49876,ENH: Add support for ea dtypes in merge,...,NaT,MEMBER,NaN,- [x] closes #44240 (Replace xxxx with the Git...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,0.0,{'url': 'https://api.github.com/repos/pandas-d...
12,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/49875,1462470373,PR_kwDOAA0YD85DmbIh,49875,BUG: constructors,...,NaT,MEMBER,NaN,- [x] closes #49292 (Replace xxxx with the Git...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,0.0,{'url': 'https://api.github.com/repos/pandas-d...
13,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/49874,1462409317,I_kwDOAA0YD85XKphl,49874,DOC: Table Visualization gets Error for cell,...,NaT,CONTRIBUTOR,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,NaN,NaN
14,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/49873,1462407665,PR_kwDOAA0YD85DmNZe,49873,Remove inline from cython classes,...,NaT,MEMBER,NaN,Part of #33926 adding `-Winline` to the compil...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,0.0,{'url': 'https://api.github.com/repos/pandas-d...
15,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/49872,1462363460,I_kwDOAA0YD85XKeVE,49872,ENH: read_excel: Add a callable to access the ...,...,NaT,NONE,NaN,### Feature Type\r\n\r\n- [X] Adding new funct...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,NaN,NaN
16,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/49871,1462353834,I_kwDOAA0YD85XKb-q,49871,DOC: Update Benchmark Link,...,NaT,MEMBER,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,NaN,NaN
17,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/49870,1462312453,PR_kwDOAA0YD85Dl4Td,49870,CI/BENCH: Make CategoricalIndexIndexing benchm...,...,NaT,MEMBER,NaN,Resizing `data_unique` to be the same length a...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,0.0,{'url': 'https://api.github.com/repos/pandas-d...
18,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/49869,1462237241,PR_kwDOAA0YD85Dlnnx,49869,API: series int-slicing always positional,...,NaT,MEMBER,NaN,- [x] closes #49612 (Replace xxxx with the Git...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,0.0,{'url': 'https://api.github.com/repos/pandas-d...
19,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/49868,1462186527,PR_kwDOAA0YD85DlcZu,49868,Backport PR #49864 on branch 1.5.x (REGR: Data...,...,NaT,CONTRIBUTOR,NaN,Backport PR #49864: REGR: DataFrameGroupBy.tra...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,0.0,{'url': 'https://api.github.com/repos/pandas-d...
20,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/49867,1462048071,I_kwDOAA0YD85XJRVH,49867,BUG: `pd.Index.str.split` has an unexpected re...,...,NaT,NONE,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,reopened,NaN,NaN
21,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/49862,1461438205,I_kwDOAA0YD85XG8b9,49862,BUG: read_csv does not comply with the to_csv ...,...,NaT,NONE,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,NaN,NaN
22,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/49861,1461416611,I_kwDOAA0YD85XG3Kj,49861,json_normalize - incorrect removing separator ...,...,NaT,NONE,NaN,```\r\nprint(pd.__version__)\r\njsn={'_id':{'a...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,NaN,NaN
23,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/49859,1461136042,PR_kwDOAA0YD85Dh1sI,49859,WEB: Formalize workgroups,...,NaT,MEMBER,NaN,Adding to our `Team` page the different workgr...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,0.0,{'url': 'https://api.github.com/repos/pandas-d...
24,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/49858,1461116952,PR_kwDOAA0YD85DhxaJ,49858,DOC: Add release process to the docs,...,NaT,MEMBER,NaN,"This was in a branch in the release repo, and ...",{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,0.0,{'url': 'https://api.github.com/repos/pandas-d...
25,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/49857,1461079459,I_kwDOAA0YD85XFk2j,49857,RLS: pandas 1.5.3,...,NaT,MEMBER,NaN,"Planned for mid-December, if nothing is requir...",{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,NaN,NaN
26,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/49856,1461035890,PR_kwDOAA0YD85Dhe8D,49856,fixed bug in tz_localize to throw an error if ...,...,NaT,NONE,NaN,- [x] closes #49565 \r\n- [x] [Tests added and...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,0.0,{'url': 'https://api.github.com/repos/pandas-d...
27,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/49852,1460858362,PR_kwDOAA0YD85Dg2Qy,49852,DOC/REF: Clarify pip extras dependencies & cle...,...,NaT,MEMBER,NaN,Clarifying that https://github.com/pandas-dev/...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,0.0,{'url': 'https://api.github.com/repos/pandas-d...
28,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/49848,1460727230,PR_kwDOAA0YD85DgZLE,49848,48855 style fix pylint issues,...,NaT,CONTRIBUTOR,NaN,- [ ] closes #xxxx (Replace xxxx with the GitH...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,1.0,{'url': 'https://api.github.com/repos/pandas-d...
29,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/49845,1460613030,I_kwDOAA0YD85XDy-m,49845,REF: Move `to_dict` implementation to pandas.io,...,NaT,MEMBER,NaN,Ref: https://github.com/pandas-dev/pandas/pull...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,None,NaN,NaN

In [26]:
js.columns

Index(['url', 'repository_url', 'labels_url', 'comments_url', 'events_url',
       'html_url', 'id', 'node_id', 'number', 'title', 'user', 'labels',
       'state', 'locked', 'assignee', 'assignees', 'milestone', 'comments',
       'created_at', 'updated_at', 'closed_at', 'author_association',
       'active_lock_reason', 'body', 'reactions', 'timeline_url',
       'performed_via_github_app', 'state_reason', 'draft', 'pull_request'],
      dtype='object')

In [27]:
js['user'][0]

{'login': 'YarShev',
 'id': 26389732,
 'node_id': 'MDQ6VXNlcjI2Mzg5NzMy',
 'avatar_url': 'https://avatars.githubusercontent.com/u/26389732?v=4',
 'gravatar_id': '',
 'url': 'https://api.github.com/users/YarShev',
 'html_url': 'https://github.com/YarShev',
 'followers_url': 'https://api.github.com/users/YarShev/followers',
 'following_url': 'https://api.github.com/users/YarShev/following{/other_user}',
 'gists_url': 'https://api.github.com/users/YarShev/gists{/gist_id}',
 'starred_url': 'https://api.github.com/users/YarShev/starred{/owner}{/repo}',
 'subscriptions_url': 'https://api.github.com/users/YarShev/subscriptions',
 'organizations_url': 'https://api.github.com/users/YarShev/orgs',
 'repos_url': 'https://api.github.com/users/YarShev/repos',
 'events_url': 'https://api.github.com/users/YarShev/events{/privacy}',
 'received_events_url': 'https://api.github.com/users/YarShev/received_events',
 'type': 'User',
 'site_admin': False}

In [29]:
df=pd.read_excel("Attribute DataSet.xlsx")

In [30]:
df

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid,1
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [31]:
df.to_json('test321.json')

In [32]:
pwd

'C:\\Users\\dell'

In [33]:
df

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid,1
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [37]:
df.to_csv("D:\\test321.csv",index=False)